services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    entrypoint: >
      bash -c "
      echo 'Iniciando o PostgreSQL...' &&
      docker-entrypoint.sh postgres &
      sleep 5 &&
      psql -U ${POSTGRES_USER} -d postgres -c 'CREATE DATABASE ${POSTGRES_DB_NOTIFICATION};' &&
      wait
      "
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8087:80"
    depends_on:
      - db


volumes:
  pgdata: